version: 0.2
phases:
    install:
        commands:
            - 'touch .npmignore'
            - 'rm ./package-lock.json'
    pre_build:
        commands:
            - 'npm install'
    build:
        commands:
            - 'npm run build'
artifacts:
    base-directory: public
    files:
        - '**/*'
