version: 0.2
phases:
    install:
        commands:
            - 'touch .npmignore'
            - 'rm ./package-lock.json'
            -  'curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && apt-get install -y nodejs'
    pre_build:
        commands:
            - 'npm install'
    build:
        commands:
            - 'npm run build'
artifacts:
    base-directory: public
    files:
        - '**/*'
